version: "2"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.8.1
    restart: always
    network_mode: host
    environment:
      - cluster.name=jgBay-cluster
      - http.host=0.0.0.0
      - network.publish_host=127.0.0.1
      - transport.tcp.port=9300
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - "xpack.security.enabled=false"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - esdata:/data/alshub/elasticsearch/data
volumes:
  esdata:
    driver: local
